.gitignore, ABloom/ABloom.xcodeproj/project.pbxproj, ABloom/ABloom.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ABloom/ABloom/ABloom.entitlements, ABloom/ABloom/ABloomApp.swift, ABloom/ABloom/Firebase/Authentication/SignInAppleHelper.swift, ABloom/ABloom/GoogleService-Info.plist, ABloom/ABloom/Login/LoginView.swift, ABloom/ABloom/Login/LoginViewModel.swift, ABloom/ABloom/Login/SubViews/AppleLoginButtonViewRepresentable.swift
애플 로그인을 구현하였습니다.
- 애플리케이션에서 애플 로그인을 할 수 있도록 구현하였습니다.
- Firebase의 Authentication을 통해 인증하는 기능을 구현하였습니다.
- 애플 로그인 버튼을 SwiftUI에서 사용하기 쉽도록 UIViewRepresentable을 구현하였습니다.
- Apple 로그인만 집중적으로 구현하다보니, 클래스 내부에 함수의 무게가 조금 무거운 경향이 있습니다.
- 로그인 기능만 구현이 되어있어, 추후 로그아웃 기능또한 구현할 필요가 있습니다.
- 내용은 Firebase의 기본 가이드라인을 기반으로 하여, 메서드들의 주석만 참고하시면 됩니다.
|로그인뷰|애플 로그인 뷰|
|------|---|
|![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/6e9bb2a7-a1d4-4352-8fb5-121704627fc2)|![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/7602ff4a-fe4e-4b4f-a0b4-917c6795866a)|
|비밀번호 입력|로그인 성공 시 데이터 출력|
|------|---|
|![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/453fb769-3191-44c6-981c-c86f97ed317b)|![image](https://github. …
=> [Feature/#12] 애플 로그인 기능 구현

ABloom/ABloom/Components/InputFieldModifier.swift, ABloom/ABloom/Presentation/Registration/View/RegistrationView.swift, ABloom/ABloom/Presentation/Registration/ViewModel/RegistrationViewModel.swift
유저 정보 입력화면에 디자인을 적용합니다.
참고할 부분은 코멘트로 남겨두겠습니다! 
네비게이션으로 연결해두지 않아서 title이 뜨지 않습니다 !
title이 커스텀폰트여서 추후에 다른 뷰와 같이 작업할 듯 합니다 !
=> [Design/#22] 유저 정보 입력 화면 디자인 적용

ABloom/ABloom/Presentation/BoundaryViews/Login/LoginView.swift, ABloom/ABloom/Resources/Extensions/Ex+Shape.swift
로그인뷰 레이아웃을 적용하였습니다.
SE에서도 화면이 깨지지 않도록 작업하였습니다.
로그인뷰의 챗버블에 쓰이는 스타일이 스타일가이드에 있는 것이 아닌 커스텀된 스타일이어서 새로 추가해두었습니다!
로그인뷰의 챗버블을 구현할 때 view Extension에서 구현한 cornerRadius 와 loginChatBubbleShadow를 같이 사용하면 
원래 의도와 다르게 적용되어서, 원래 사이즈보다 너비를 키우고 offset으로 이동시키는 방식으로 구현했습니다.
=> [Feat/#46] 로그인뷰 레이아웃 적용

ABloom/ABloom/Presentation/BoundaryViews/Login/LoginView.swift, ABloom/ABloom/Presentation/BoundaryViews/Login/LoginViewModel.swift
로그인뷰 하단의 이용약관 및 처리방침을 클릭했을 시 웹사이트가 모달로 나오도록 구현합니다.
로그인뷰의 이용약관 및 처리방침이 모달로 나오도록 구현하였습니다.
간단한 기능 구현 내용입니다 !
=> [Feat/#53] 로그인 뷰 - 개인정보처리방침, 이용약관 클릭 시 웹뷰 sheet 띄우기

ABloom/ABloom.xcodeproj/project.pbxproj, ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift, ABloom/ABloom/Resources/Components/CustomNavigationBarModifier.swift, ABloom/ABloom/Resources/Components/QnAListItem.swift, ABloom/ABloom/Resources/Extensions/Ex+Shape.swift, ABloom/ABloom/Resources/Extensions/Ex+View.swift
- Question 탭에 연결되어 있는 3개의 뷰 디자인 수정 (WriteView는 이전에 수정함)
컴포넌트는 우선 제가 사용하는 뷰에서 조절하였습니다. 
다음 이슈 때는 챗 버블과 쉐도우 포함 전반적인 컴포넌트를 수정하도록 하겠습니다. :)
Bentley -> 이미지에 inner shadow를 덮는 과정을 완료하지 못했습니다. 이미지 자체 배경 칼라에 쉐도우를 입히기 위해서 여러방법으로 시도했지만 찾지 못해 다른 방안을 모색, 지금 shadow로 지정, 혹은 둘 사이의 합의점을 찾으면 좋을 것 같습니다.
| Main | Question | AnswerCheck |
|--------|--------|--------|
| ![Main](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/53145c7a-539d-48bd-95eb-7f5925cd678b) | ![Question](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/23f7ea7c-cce2-4abc-bbff-c25f91a5bcb2) | ![Check](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/b2eef301-b528-4250-8db1-d6e0afce047c) |
X
=> [Design/59] QuestionView 디자인 수정 및 완료

ABloom/ABloom/Firebase/Firestore/UserManager.swift, ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift, ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountViewModel.swift
내 계정 뷰에서 할 수 있는 동작들을 구현하였습니다.
- 이름 변경 기능 구현
- 결혼 예정일 변경 기능 구현
- 로그아웃 안내 모달 구현
@JINi0S 의 데이트 피커를 참고하여 결혼 예정일 변경 기능을 구현하였습니다.
|정보 변경 액션시트|이름 변경|
|---|---|
|<img width="511" alt="Untitled" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/aec1d4c4-5651-4f20-84a8-d52cd909f97e">|<img width="511" alt="Untitled" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/9fde83f9-a807-4c7a-bd22-5308fc9bda5b">|
|캘린더 뷰|변경 동작 실행 후|
|---|---|
|<img width="511" alt="Untitled" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/1005df82-afe2-49a6-bdd9-315f6808cabb">|<img width="511" alt="Untitled" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/e26fdf3f-0b4f-45e1-9683-a5382eae57 …
=> [Feat/#69] 내 정보 수정 구현

ABloom/ABloom.xcodeproj/project.pbxproj, ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift, ABloom/ABloom/Firebase/Firestore/UserManager.swift, ABloom/ABloom/Firebase/Model/DBAnswerModel.swift, ABloom/ABloom/Firebase/Model/DBStaticQuestionModel.swift, ABloom/ABloom/Firebase/Model/DBUserModel.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift, ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift, ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift, ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift, ABloom/ABloom/Resources/Components/QnAListItem.swift, ABloom/ABloom/Resources/Extensions/Ex+ Query.swift
질문에 응답하는 기능을 구현했습니다.
- 응답 생성하기: 사용자가 질문에 응답하면, 그 값을 Firestore에 저장합니다.
- 답변 시 해당 문항 질문 선택 리스트에서 제거: 질문을 불러올 때, 이미 답변한 질문은 제외하고 가져옵니다.
- 답변된 질문을 '질문 메인 뷰'에 표시
- 답변 확인 뷰에 질문 연동
@Hayun218: 문답 확인 뷰에 CategoryQuestionBox 레이아웃을 수정해주세요. 결과화면에 첨부하겠습니다!
|응답 보기|응답된 질문은 선택화면에서 제외|답변 확인뷰 질문 연동|
|---|---|---|
|<img width="511" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/f29440bf-a47a-4c14-bdf4-89e0989af35c">|<img width="511" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/9d3454d1-33e8-4c2a-bebb-b2f93389b33c">|<img width="511" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/582a562a-a6e3-491a-992f-990ae73a850a">|
매니저의 역할이 헤비해진 관계로 코드 가독성을 위해, 파이어 스토어에서 사용하는 …
=> [Feat/#72] 응답 기능 구현

ABloom/ABloom.xcodeproj/project.pbxproj, ABloom/ABloom/Presentation/CoreViews/Home/ImageFileManager.swift, ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift, ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
홈화면의 이미지를 로컬에 저장하고 불러오도록 구현하였습니다.
ImageFileManager를 지금은 Presentation/Home 아래에 넣었는데, 어디에 넣으면 좋을까요?!
Utilities, Classes, Managers 폴더 등,,,
라이브러리 접근 권한 설정에 따른 분기는 추후 구현 예정입니다 !
=> [Feat/#70] 홈화면 이미지 로컬 저장 및 불러오기 구현

ABloom/ABloom.xcodeproj/project.pbxproj, ABloom/ABloom/Presentation/BoundaryViews/Connection/ConnectionView.swift, ABloom/ABloom/Presentation/BoundaryViews/Registration/View/RegistrationView.swift, ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/Components/EmbedWebView.swift, ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift, ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectedView.swift, ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingView.swift, ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/PolicyView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift, ABloom/ABloom/Resources/Components/CustomNavigationBarModifier.swift, ABloom/ABloom/Resources/Components/NavigationArrowLeft.swift
커스텀 네비게이션바 타이틀 모디파이어 수정 밎 모든 뷰에 적용하였습니다.
모든 뷰의 네비게이션바 타이틀을 수정하였습니다.
네비게이션바 모디파이어 아래에 백그라운드모디파이어가 적용되어야해서 순서를 수정했습니다.
리뷰어의 이해를 위해 스크린샷을 추가해주세요.
=> [Design/#81] 커스텀 네비게이션바 모디파이어 수정 및 뷰 적용

ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift, ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift, ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift, ABloom/ABloom/Resources/Components/CategoryQuestionBox.swift, ABloom/ABloom/Resources/Components/ChatBubbles.swift
- DB 연결 로직을 문답 뷰와 연결
- ChatBubble 컴포넌트 생성 및 수정
- User의 성별 가지고 오기
- 성별 및 답변 현황에 따라서 뷰 구현하기
User 성별 가지고 올 때, AnswerWriteView에 파라미터로 넘길 시 버그가 발생했습니다. 네비게이션에 해당하는 버그 같아서 로직 상의 문제가 아니라, AnswerWriteViewModel에서도 똑같이 유저 성별을 가지고 오는 함수를 구현해 두었습니다.
챗버블 코드 내부에서 마크 주석으로 분리해두었는데, 나중에 정리해보겠습니다!
상황 별로 달라서 규니 로직과 합친 이후 확인해 보겠습니다!
X
=> [Feat/80] DB 연관 뷰 로직 수정

ABloom/ABloom.xcodeproj/project.pbxproj, ABloom/ABloom/Firebase/Firestore/UserManager.swift, ABloom/ABloom/Firebase/Model/DBAnswerModel.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift, ABloom/ABloom/Resources/Components/QnAListItem.swift
상대 답변을 메인 화면에 불러오고, 질문의 답변 상태에 따라 뷰 상태를 변경하도록 구현하였습니다.
- 상대방 답변 불러오기
- 질문 정렬 및 답변 정렬 (최신 날짜 순)
- extension 하나 추가했습니다. 배열에서 중복 값 제거하는 함수를 추가했습니다.
- 답변 상태를 enum으로 구현했습니다.
- 정렬 및 필터링 기능을 손수 구현했습니다. 더럽더라도 봐주세요. 🙇‍♂️
=> [Feat/#77] 상대 답변에 따른 답변 메인 화면 로직 구현

ABloom/ABloom.xcodeproj/project.pbxproj, ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/DeleteAccountView.swift, ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift, ABloom/ABloom/Resources/Components/CustomNavigationBarModifier.swift
회원탈퇴 뷰 레이아웃을 구현합니다.
네비게이션바 타이틀 색상을 .stone800으로 수정했습니다.
화면 이동과 기능을 제외하고 뷰를 구현했습니다.
없습니다
=> [Design/83] 회원탈퇴 뷰 레이아웃 구현

ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift, ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift
질문 선택하기 뷰에서 질문을 선택할 때, 상대방이 이미 작성한 질문도 가져오지 않도록 수정했습니다.
- getQuestionsWithoutAnswers()메서드를 수정하였습니다.
- 자잘한 코드를 수정했습니다.
결과 화면 참고.
=> [Feat/#87] 상대방이 답변한 질문도 리스트에서 뜨지 않도록 수정

ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift
- AnswerWrite에서 작성한 텍스트가 없을 때, 처리
- 벤틀리와 상의하여 Flow 적용
- 작성한 텍스트 없을 시, 
1. "완료" 버튼 비활성화
2. 뒤로 가기 버튼 클릭시 "삭제하시겠어요?" 얼럴트 창 나타나지 않고 dismiss
질문을 fetch 하는 코드에서 task 처리를 규니가 하고 있어서, develop에서 에러가 발생했었습니다!
그래서 로직 구현만 하고 확인은 못해서 규니 코드 merge 후 다음 PR에서 이 부분도 같이 확인하겠습니다.
X 
X
=> [Bug/90] AnswerWrite Empty일 때, 처리

ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
질문 가져오기 시, 비교 쿼리 값으로 10개 이상 입력되면 쿼리가 동작하지 않는 현상을 발견했습니다.
모든 질문을 가져온 뒤, 클라이언트 내부에서 필터링을 하는 방식으로 수정하였습니다.
결과화면 참고
=> [Fix/#109] 질문 가져오기 로직 수정

ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift, ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift, ABloom/ABloom/Resources/Components/QnAListItem.swift
- 배포 전 버그 찾기 및 수정
- 문답 탭에서 스크롤 버그 해결
- 새로 유저 생성 후 문답 탭 이동시 빈 배열로 인한 오류 해결 (규니)
- 배열이 비어있을 경우와 비어있지 않을 경우 우선 초기 스크린은 하얀 배경으로 설정
- 답변사항이 불러와 정렬 될 때, progressView로 대체
- AnswerWrite 뷰에 "연결하기" 버튼 패딩 값 조절
계속해서 찾고 수정하겠습니다 :)
| Progress | Padding 조절 |
| ![Simulator Screenshot - iPhone 15 Pro - 2023-10-31 at 12 20 28](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/8981c64f-7ff1-41e5-aacd-ebeb948c9474) | ![Simulator Screenshot - iPhone 15 Pro - 2023-10-31 at 12 13 40](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/ddde407e-2212-4016-814d-b11ddd81a329) | 
X
=> [Chore/111] ScrollView 수정, answers 빈 배열 수정(규니), 비었을 때 뷰 수정

ABloom/ABloom.xcodeproj/project.pbxproj
사진 라이브러리 접근 권한 문구 수정
접근 권한 문구를 "예랑이/예신이와 함께 찍은 사진이 담긴 나만의 홈화면을 만들기 위해 사진 라이브러리에 접근하도록 허용합니다."로 수정합니다.
없습니다
=> [Chore/#129] 사진라이브러리 접근 권한 문구 수정

ABloom/ABloom.xcodeproj/project.pbxproj, ABloom/ABloom/Resources/Extensions/Ex+UINavigation.swift
스와이프 백 구현
UIKit Extension 활용하는 코드 첨부 
NavigationStack 뷰에 자동 적용되어 따로 코드 추가하지 않아도 됩니다.
X
=> [Bug/#132] SwipeBack 구현

ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectedView.swift, ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectionWaypointView.swift, ABloom/ABloom/Resources/Components/InputFields.swift, ABloom/ABloom/Resources/Utilities/ServiceWebURL.swift
상대방과 연결 뷰에서 나의 코드를 볼 수 있도록 수정하였습니다.
- 연결 상태 메세지 폰트 수정
- 연결 코드 박스 컴포넌트 디자인 수정
- 연결 코드 박스 뷰 추가
- 레이아웃 수정
- 너무 기능이 심플한 것 같아서, 따로 ViewModel을 정의하지 않고 뷰에서 기능들을 구현하였습니다. 필요하다면 뷰모델을 구현하도록 하겠습니다.
- 기능 테스트를 위해 임의로 배찌와 연결하고, 삭제하였습니다.
|연결 완료 뷰|복사 시 토스트메세지|
|---|---|
|<img width="511" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/d4c63a42-6b0f-4396-b582-7e7cfec7413d">|<img width="511" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/c01d1eab-eca0-4d05-ad6c-ed44f7d5cd78">|
=> [Feat/#147] 상대방과 연결 뷰에서 나의 코드를 볼 수 있도록 수정하였습니다.

ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift, ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift
질문선택뷰의 질문이 qid에 따라 정렬되지 않아 있던 부분을 수정하였습니다.
질문선택뷰의 질문을 오름차순으로 정렬하였습니다.
원본배열을 정렬하기 위해 sort를 사용하였습니다
=> [Bug/#144] SelectQuestionView 질문 오름차순 정렬

ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift, ABloom/ABloom/Resources/Extensions/Ex+Date.swift
추천질문 업데이트 날과 현재 날을 비교하고 저장하는 부분이 한 번 꼬여있어, 3시에 변경되는 걸로 계산되어 있던 부분을 수정하였습니다.
지난 업데이트날짜와 현재 날짜를 UTC +0으로 두고, 
같은 날인지 확인하는 부분에서 UTC +9 (아시아/서울) 시간대로 변경하여 비교하도록 수정하였습니다.
=> [Bug/#131] 추천질문 변경 날짜 한국시간으로 수정

ABloom/ABloom.xcodeproj/project.pbxproj, ABloom/ABloom/ABloomApp.swift, ABloom/ABloom/Info.plist, ABloom/ABloom/LocalPushNotification.swift
- 정해진 시간에 알림을 보내는 로컬 푸쉬 기능 구형
AppDelegate 파일에 설정해 두어야 하는데, 이전 PR에서 리팩토링하여 컨플릭트가 우려되서 다른 파일에 만들어두었습니다.
그리고 Firebase 쪽 코드와 합쳐지는 것을 고려했을 때, 아직 정확히 이해하지 못해 따로 먼저 구현해 보았습니다.
멘트나 시간에 대해서는 제이와 벤틀리한테 요청해둔 상태이고, 이번주 중에 네트워크 푸쉬도 공부하면서 합쳐보겠습니다!
이슈에 작성한 것 처럼 ON/OFF 기능 고려하면서 구현한다고 했는데, 함수 실행할 때, 설정에서 받아온 변수로 처리하면 될 듯 합니다.
아직 설정에서 셋팅하는 기능이 없어서 우선은 어떻게 할지만 구상하고 넘어갔습니다.
* 알림은 앱을 백그라운드에서 껐을 때도 동작하고, 알림을 눌렀을 때, 앱으로 바로 이동하게 됩니다!
* 적다가 생각났는데, 실행 중에도 알림이 오는지는 확인하지 않았습니다,, 안왔던것 같은데, 앱을 구동할 때는 알림이 필요없다고 생각하는데, 필요하다고 하면 따로 구현하겠습니다!
* plist 다크모드 차단한 코드가 추가되었는데, 이건 이전에 말한바와 같이 자동 생성된 파일에서 연동 될때가 있고 안될때가 있어서, 자동 생성된것 같습니다~ 제가 따로 직접 만진건 아닙니다,,
X
=> [Feat/#159] 로컬 푸쉬 기능 구현, 내용은 미확정

ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
- 질문선택뷰에서 카테고리 변경 시 스크롤이 유지되는 현상 해결
- ScrollViewReader 도입으로 카테고리가 변경될 경우, 상단으로 이동하도록 해결
- padding 값 피그마 보고 눈대중으로 재조정
- bottom 부분에 패딩 추가하여 사용성 부분 개선
1. onChange에 new 값을 안 적으면, 17버전에서만 사용되는 함수라고 되어서, 안쓰는 변수이지만 기존 onChange 함수에서 쓰는 것처럼 추가해 두었습니다.
2. forEach 문 내부에서는 VStack(spacing) 값이 통하지 않아 일일히 패딩 적용하였습니다.
3. top 패딩 대신 가장 상단의 Spacer 부분의 값을 조정하였습니다.
4. 카테고리 제목이 차지하는 뷰가 많아서 스크롤시 조금 줄였습니다.
X
=> [Bug/#141] 카테고리 변경시 상단으로 스크롤

ABloom/ABloom/Presentation/CoreViews/Home/View/HomeRecommendView.swift, ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift, ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
홈뷰 레이아웃과 버그를 수정하였습니다.
HomeView Appear시 실행되는 중복 태스크를 일부 수정하였습니다.
홈뷰 사진의 경우 높이를 380으로 고정해두면 SE에서 길어져 최소최대값을 주는 방식으로 적용하였습니다.
기존에 onAppear과 task로 분리되어있던 부분을 task로 변경하고,
.task(id: showLoginView) {}을 Sheet가 사라질 경우 실행되도록 수정하였습니다.
=> [Feat/#135] 홈뷰 레이아웃 수정, 상대방 성별 불러오기

ABloom/ABloom.xcodeproj/project.pbxproj, ABloom/ABloom/Presentation/BoundaryViews/Registration/View/RegistrationView.swift, ABloom/ABloom/Presentation/BoundaryViews/Registration/ViewModel/RegistrationViewModel.swift, ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift, ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift, ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountViewModel.swift, ABloom/ABloom/Resources/Utilities/UserSexType.swift
유저가 신랑인 경우에도 메뉴 프로필 아이콘에 신부아이콘이 뜨는 현상을 해결했습니다.
- View Model에 user의 Sex 값을 받을 수 있도록 프로퍼티를 추가하였습니다.
- UserType이라는 열거형을 Resources의 Utilities 그룹으로 이동 후 UserSexType으로 변경하였습니다.
- UserSexType에 초상화 이미지 이름을 가져오는 함수를 추가하였습니다.
- 유저의 Sex 값에 따라 초상화 이미지가 변경되는 로직을 구현하였습니다.
- 유저 모델에 UserSexType를 출력하는 Method or Computed Property를 추가하여 개선할 수 있을 것 같습니다. 추후 성별이 적용되는 뷰에 적용할 수 있도록 하면 좋을 것 같습니다.
=> [Bug/#161] 성별에 따른 초상화 이미지 변경 기능 구현

ABloom/ABloom.xcodeproj/project.pbxproj, ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift, ABloom/ABloom/Resources/Components/QnAListItem.swift, ABloom/ABloom/Resources/Utilities/AnswerStatus.swift, ABloom/ABloom/Resources/Utilities/Category.swift
QuestionMainView에 사용되는 문답 리스트 컴포넌트와 뷰를 수정했습니다.
- QnaListItem 안에 쓰이는 태그 컴포넌트들은 다른 뷰에서 재사용되고 있지 않기 때문에 
따로 파일을 구분짓지 않고 뷰 내에 구현하였습니다.
- Enum으로 되어있는 부분을 Utilities폴더로 이동시켰습니다.
- QuestionMainView내에 뷰 상태를 관리하는 enum을 생성하여 변수 하나로 상태변화를 구분짓도록 했습니다.
Feat로 작업했는데 Design에 가까워서 라벨을 변경하였습니다요!
=> [Design/#172] 문답리스트 뷰 수정

ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift, ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift, ABloom/ABloom/Resources/Components/ChatBubbles.swift, ABloom/ABloom/Resources/Extensions/Ex+UINavigation.swift
스프린트2 AnswerWriteView 수정
- 텍스트필드에서 기존 커서가 시스템 폰트로 진행되서 글자 입력 시 커서가 줄어들고, 동시에 백그라운드도 줄어드는 현상 방지를 위해 minHeight 조정했습니다. (여러가지 시도를 했지만 못찾았습니다;; 추천방법이 있을까요?)
- AnswerWriteView에서 텍스트를 입력하고 뒤로가기 버튼 클릭시 경고창이 뜨는데, 스와이프 백을 했을 때는 그런게 없어서, 그 뷰에서만 스와이프백을 못하게 처리했습니다.
1. 텍스트필드 관련 사항 혹시 해결 방법이 있을까요? 
(overlay하는 방법도 고려했습니다만 geometryReader쓰고 일일히 조절해줘야해서, 리소스 낭비라는 생각이 들었습니다!)
2. 스와이프백 관련 QuestionMainView에서도 다시 true로 바꿔줘야하는데 라딘 코드와 충돌될 것 같아서 하지 않았습니다!
3. 스와이프백 관련 벤틀리와 이야기했던 사항이라 적용했는데, 내일 세션 중에 다시 한번 더 이야기해보겠습니다!
X
=> [Feat/#176] AnswerWriteView 텍스트필드 및 스와이프 제한 적용

ABloom/ABloom.xcodeproj/project.pbxproj, ABloom/ABloom/Presentation/CoreViews/Menu/MenuView.swift, ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/DeleteAccountView.swift, ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift, ABloom/ABloom/Presentation/CoreViews/TabBar/TabBarView.swift
로그아웃 후 재로그인 시 홈화면이 아닌 다른 화면으로 이동되는 이슈를 해결하였습니다.
- binding을 이용하여 Tab 화면을 제어합니다.
- 버전 표시, 프로젝트 버전을 수정하였습니다.
- 회원 탈퇴 시 플로우는 품이 많이 들어갈 것 같아, 추후 리팩토링 때 NavigationPath를 통해 구현할 수 있도록 하겠습니다!
=> [Bug/#149] 로그아웃 플로우 수정

ABloom/ABloom/Presentation/CoreViews/QnA/View/TipView.swift
TipView레이아웃을 수정하였습니다.
@kimyejoon 확인 부탁드림다. 자간을 -0.4로 하면 "."만 다음 줄로 넘어가서 자간을 일부 수정하였습니다.
@Hayun218 저 .useNonBreakingSpace()는 이렇게 쓰는 게 최선이겠죠?,,!?!
| SE | 15 plus |
| ![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/100195563/2072a081-a11a-4137-b1fc-f1f09b93b8be) | ![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/100195563/5e703529-3f91-4049-bcd1-6999a334aedb) |
=> [Design/#197] Tipview 레이아웃 수정

ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift, ABloom/ABloom/Resources/Components/ChatBubbles.swift
챗버블 버튼 디자인 수정
- ChatBubbleBtn 수정
- 문장 개행하는 모디파이어 위치를 컴포넌트 내로 수정 (QuestionSelection 에만 해당)
문자 개행하는 모디파이어가 어디어디 쓰이는지 정리되면 컴포넌트 내에서 처리해도 좋을 것 같습니다!
X
=> [Design/#205] ChatBtn 크기 및 폰트 수정

ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
QA 해결, 로그아웃 시 로그인 화면이 두 개가 표시되는 문제 해결
=> [Bug] QA 해결, 로그아웃 시 로그인 화면이 두 개가 표시되는 문제 해결

ABloom/ABloom.xcodeproj/project.pbxproj, ABloom/ABloom/Presentation/1.0/CoreViews/QnA/View/QuestionMainView.swift, ABloom/ABloom/Presentation/1.0/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift, ABloom/ABloom/Presentation/Main/QnAList/QnAListItem.swift, ABloom/ABloom/Resources/Assets.xcassets/colors/StatusColor/Complete.colorset/Contents.json, ABloom/ABloom/Resources/Assets.xcassets/colors/StatusColor/Contents.json, ABloom/ABloom/Resources/Extensions/Ex+Date.swift, ABloom/ABloom/Resources/Utilities/AnswerStatus.swift
홈화면의 QnAListItem 컴포넌트에 디자인을 적용시켰습니다.
벤틀리와 논의한대로 이번 스프린트에서도 문답 상태를 태그 방식으로 나타내기로 하였고, 그에 따라 디자인을 적용하였습니다.
홈화면에 컴포넌트 그리는 작업을 하면서 수정이 더 있을 듯합니다!
=> [Design/#233] QnAListItem 컴포넌트 디자인 적용

ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointView.swift, ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointViewModel.swift, ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift, ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionViewModel.swift, ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerView.swift, ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerViewModel.swift, ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
웨이포인트, 질문선택, 답변작성 뷰들간 연결 구현
- 시트 자체를 끄기 위해서 Binding을 파라미터로 전달하는 형태로 구현 (dismiss는 현재 뷰만 끌 수 있음)
- 카테고리를 선택하여 들어 온 후 변경하고 작성 뷰에서 dismiss할 경우 처음 선택한 카테고리로 돌아오는 버그 해결
- 답변작성 뷰에서 텍스트가 있을 경우, 백 스와이프 방지, 스와이프 다운으로 시트 해제 방지
답변작성 뷰에서 Alert 창은 디펄트로 하기로 해서 그대로 유지합니다!
뷰가 바뀌지 않아서 결과화면은 첨부하지 않았습니다.
X
=> [Feat/#252] 뷰 간 이동 구현

ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift, ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift, ABloom/ABloom/Resources/Utilities/UserSexType.swift
문답리스트뷰의 프로필 이미지를 적용합니다.
문답리스트뷰에서 프로필이미지를 추가했습니다.
없쓰으음니다!
=> [Feat/#262] 문답리스트뷰(홈) 프로필 이미지 적용

ABloom/ABloom/ABloomApp.swift, ABloom/ABloom/Presentation/Main/QnAList/QnAListItem.swift, ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift, ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift, ABloom/ABloom/Resources/Assets.xcassets/Images/LogoPurple.imageset/Contents.json, ABloom/ABloom/Resources/Assets.xcassets/Images/LogoPurple.imageset/MeryLogo_Flat_Purple600@SVG.svg, ABloom/ABloom/Resources/Utilities/AnswerStatus.swift, ABloom/ABloom/Resources/Utilities/UserSexType.swift
문답리스트뷰의 문답 데이터를 연결합니다.
Static질문을 fetch하지 않으면 다른 부분이 동작을 안해서 이 뷰에서도 하도록 해두었습니다..
커플문답이 [질문:[답변]]으로 구성되도록,,,해두었음다...
문답 상태 코드가 개빡시잉디...상태에 따라 다 맞게 나오는지는 다음 작업에서 확인하면서 다시 수정하겠음다..
=> [Feat/#261] 문답리스트뷰 문답 데이터 연결 

ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift, ABloom/ABloom/Firebase/Firestore/AnswerManager.swift, ABloom/ABloom/Firebase/Firestore/ConnectionManager.swift, ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift, ABloom/ABloom/Firebase/Firestore/UserManager.swift, ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectionViewModel.swift, ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuView.swift, ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuViewModel.swift, ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift, ABloom/ABloom/Presentation/SignUp/SignUpViewModel.swift
회원가입과 프로필 메뉴에서 입출력 동작이 있을 경우 데이터를 동기화 할 수 있는 로직을 추가하였습니다.
- Combine을 이용하여 Model과 ViewModel 간의 데이터를 동기화할 수 있도록 구현하였습니다.
- 회원가입, 이름 및 결혼 예정일 수정, 연결관리, 회원탈퇴, 로그아웃의 동작이 수행될 때 Model의 데이터가 최신화 될 수 있도록 각 메서드에 fetch 동작을 추가하였습니다.
- UserManager, ConnectionManager의 CUD 동작에 대해, 마무리로 데이터를 동기화 시키는 작업이 있는지 확인해주세요.
- ViewModel의 데이터가 동기화 될 수 있도록 sink 동작 메서드가 묶여있는지 확인하시면 됩니다.
=> [Feat/#270] 프로필 메뉴 및 회원가입에서 가능한 입출력 동작과 뷰 간의 Source of truth를 유지할 수 있도록 로직 구현

ABloom/ABloom/ABloomApp.swift, ABloom/ABloom/Firebase/Firestore/AnswerManager.swift, ABloom/ABloom/Firebase/Firestore/ConnectionManager.swift, ABloom/ABloom/Firebase/Firestore/UserManager.swift, ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectionViewModel.swift, ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuView.swift
Snapshot Listener를 이용하여 응답을 실시간으로 가져올 수 있는 기능을 구현하였습니다.
- addSnapshotListenerForMyAnswer() 함수 추가
- addSnapshotListenerForFianceAnswer() 함수 추가
- Snapshot Listener를 통해 데이터베이스 상 변화가 있을 시 변경을 바로 가져올 수 있도록 하였습니다.
- 아직 라딘의 QnA View가 머지 되지 않아서, 뷰의 변화는 확인하지 못했지만, 로그상으로 확인 했을 때 잘 되는 것을 확인했습니다.
- 라딘은 Combine을 이용하여 데이터를 뷰 모델로 가져오는 코드를 구현하면 될 것 같습니다. @JINi0S
=> [Feat/#279] Answer Data에 대한 Snapshot Listener 구현

ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerView.swift, ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerViewModel.swift
문답확인뷰에서 연결/작성시트 보여주기
작성한 뒤 새로 데이터를 불러오지 않아, 앱을 새로 켜야합니다.
=> [Feat/#276] 문답확인뷰 연결/작성 시트 띄우기

ABloom/ABloom/AppDelegate.swift
알림 클릭 시에만 모달이 뜨도록 하고, 앱을 사용중에는 반응하지 않도록 수정
=> [Release] noti 앱 내 모달해결

ABloom/ABloom.xcodeproj/project.pbxproj, ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift, ABloom/ABloom/Firebase/Firestore/AnswerManager.swift, ABloom/ABloom/Firebase/Firestore/UserManager.swift, ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointView.swift, ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointViewModel.swift, ABloom/ABloom/Presentation/Main/Menu/Connection/ConnectingView.swift, ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuView.swift, ABloom/ABloom/Presentation/Main/Menu/ProfileMenu/ProfileMenuViewModel.swift, ABloom/ABloom/Presentation/Main/Menu/WithdrawalMembership/WithdrawalMembershipView.swift
QA시 진행한 피드백을 수용하였습니다.
- 미로그인 시, 내 정보 수정 및 상대방과 연결 기능을 사용할 수 없어야 한다.
- 미로그인 시, 회원탈퇴, 로그아웃 사용할 수 없어야 한다.
- 로그아웃 시, 홈 화면으로 돌아가야 한다.
- 로그아웃 시, QnA List가 초기화 되어야 한다.
- 로그아웃 시, 질문을 선택할 수 없어야 한다.
- 회원탈퇴 시, 상기 로그아웃 이슈와 동일하다.
- 회원탈퇴 시, 온보딩 화면으로 이동하여야 한다.
- 연결 관리 시, 연결 코드 입력 중 키보드를 숨길 수 있어야 한다.
- 연결 하기 뷰에서 복사 기능 수행 시, 토스트 메세지가 출력되어야 한다.
- 메뉴 뷰, 문답 연구소 → 질문 제작소 라이팅 수정
=> [Bug/#289] QA 반영

ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
상대방과의 연결이 없을 시 문답리스트뷰의 프로필에서 빨간 점을 통해 알 수 있도록 합니다.
문답리스트뷰 프로필에 빨간 점을 추가하였습니다.
없씁니다.
=> [Feat/#299] 문답리스트뷰 상대방없을 시 프로필 빨간 점 추가

ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerView.swift
TextField 워드 카운트 위 영역 클릭 시 바로 작성할 수 있도록 영역 확장
- TextField에서 TextEditor로 교체
- TextEditor는 내부 패딩이 존재하고, 이를 수정할 수 없어서, 다른 패딩 값 조율하여 맞춤
- TextEditor에 따로 placeholder를 주는 방법이 없어 background로 비치 (ZStack 과 background 방법이 있었는데, 내부패딩으로 인해 일반 Text로 할경우 임의로 패딩값 설정이 필요해서 background로 TextEditor를 추가하고 opacity로 처리함)
- placeholder를 위해 opacity 값을 추가하였음. 이에 따라, 텍스트 색상 더 찐한거로 변경하여 육안상 디자인 맞춤
- 커서 색상이 기본 파란색이라서 biPurple 색상으로 바꿈
- 처음 클릭시에는 두번 탭하여야 버튼을 인식하는 듯 하고, 다음부터는 한번만 클릭해도 인식돼요.
- 카운트 영역 아래를 클릭시에는 키보드가 내려갑니다. (이전에는 텍스트 필드 영역 외부면 내려갔으나, 영역을 고정시켰기에 카운트 영역 아래 클릭해야 합니다.)
- opacity로 placeholder를 처리하여 처음 텍스트 입력할 때, 커서도 투명도가 있습니다.
https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/b7b3eb7e-e81c-4631-a911-30e8f4cc5baa
* 시뮬레이터에서 동작할 때는 키보드 관련 작업이 느리게 처리되지만, 클릭 상태 확인을 위해 위 영상 첨부
* 커서의 …
=> [Feat/#303] TextField 영역확장 (Editor로 바꿈)

ABloom/ABloom/Presentation/Main/QnAList/QnAListView.swift
메인 화면에서 플러팅 버튼의 시야를 위해 스크롤 되는 영역 확장
- 패딩 값 조절
X
| 화면 |
|--------|
| ![Simulator Screenshot - iPhone 15 Pro - 2024-01-15 at 16 51 52](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/79bac081-f662-4ae2-8723-8d66da6f0bbb) |
=> [Design/#306] scrollArea 늘리기

ABloom/ABloom.xcodeproj/project.pbxproj, ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift, ABloom/ABloom/Firebase/Authentication/SignInAppleHelper.swift
애플 로그인 시 사용자 이름 요청 제거
cf. [Slack 쓰레드](https://theabloom.slack.com/archives/C06BG91V8GP/p1708093836296099)
핫픽스 요청에 따른 애플 로그인 시 사용자 이름을 요청하는 부분을 삭제했습니다.
회원가입 플로우 진행에 아무 문제 없었습니다.
=> [Fix] HOT FIX - 애플 로그인 시 사용자 이름 요청 제거

ABloom/ABloom/Presentation/SignUp/SignUpContentView.swift, ABloom/ABloom/Resources/Utilities/ReactionType.swift
회원가입시 이름 입력하는 부분의 높이를 패딩으로 지정해두여 텍스트를 입력할 시 높이가 줄어드는 문제 해결
확인해보니까 아래의 .lineSpacing(7)이 적용되어있는 부분 때문에 높이가 유동적인 것 같습니다.
customFont 메서드 변경없이 높이만 고정해두어도 문제는 해결되어 높이만 지정하는 방식으로 수정하였씀다-!
```swift
func customFont(_ fontStyle: Font) -> some View {
self
.font(fontStyle)
.lineSpacing(7)
.tracking(-0.4)
}
```
=> [Bug/#320] 회원가입 이름 입력창 줄어드는 버그 수정

ABloom/ABloom/Presentation/SignUp/SignUpContentView.swift, ABloom/ABloom/Presentation/SignUp/SignUpViewModel.swift
(cherry picked from commit c9b5c2f7120b9daff1a808c24473ff38b3874dba)
회원 가입 플로우에 만 14세 이상임을 확인하는 장치를 추가합니다.
없씁니다
|  | |
| ![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/100195563/130aa902-0032-4625-891b-7d1fce08b61e) | ![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/100195563/3a697af8-fb46-46d8-bb76-7f63b4d286be) |
=> [Design/#328] 만 14세 이상 확인 버튼 추가

ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerViewModel.swift
- 처음부터 긍정-긍정 반응일 경우, 문답 완성 알림이 보내지지 않는 버그 수정
- is_complete 로직 처리 변경
- selectedFianceReactionType.isPositiveReact() -> checkFianceReaction() 로 변경하여 상대방의 반응에 즉각 대응하도록 함
리액션이 null에서 값이 들어와 바뀔 때, selectedFianceReactionType 이 바뀐 값이 아닌 null을 return 하고 있었음
- 나의 반응에 대해서는 반대로 selectedReactionType 변수가 변경된 값을 지니고 있어서 그대로 유지 (checkMyReaction()은 기존 DB에 있는 이전 값을 불러옴)
=> [Bug/#350] 문답완성필드로직수정

ABloom/ABloom/Firebase/Firestore/AnswerManager.swift, ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerViewModel.swift, FirebaseFunction/functions/index.js
- 리액션과 문답완성 필드가 각각 DB에 업데이트 됨에 따라 Firebase Function 반응이 2번 일어나서 한번에 긍정-긍정 반응이 될 경우, 리액션 알림과 문답완성 알림이 동시에 전송되는 버그 수정
- JS 코드에서 함수 두개를 하나로 합침 => 테스트를 위해 수정한 후, 로직에는 문제가 없고 서버에 등록된 함수 갯수를 줄일 수 있어 그대로 유지
- AnswerManger에서 리액션과 is_complete 필드를 동시에 수정 및 업데이트 가능하도록 수정
- 릴리즈 후 버그여서 우선 develop 브랜치를 base로 해두었습니다. 마이너 버그 수정으로 빠른 릴리즈해도 괜찮을 거 같고, 릴리즈 관련해서는 벤틀리, 제이와 상의가 필요합니다.
ps. 이번엔 진짜 알림 버그 완전 적용 되었다고 생각하긴 합니다만, 동시에 두 기기에서 테스트해야 하는 한계로 놓치는 부분이 계속 있었네요,, 
두 기기로 테스트하고 PR 날립니다,,
=> [Feat/#354] 알림-DB 업데이트 로직 수정

ABloom/ABloom/Firebase/ConnectionShare/KakaoShareManager.swift, ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerView.swift, ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerViewModel.swift, ABloom/ABloom/Resources/Utilities/MixpanelManager.swift
유저 트래킹을 위한 믹스패널 코드를 삽입, 수정, 구현을 하였습니다.
- 카카오톡 공유하기 기능 추적
- 답변 생성 프로퍼티 추가
- 알림 접근을 위한 메서드 작성
알림 접근에 대한 로직을 잘 몰라 구현하지 못했습니다. 추후 리아와 함께 작업할 예정입니다.
=> [Feat/#356] mixpanel 코드 삽입 및 수정, 구현
