- ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/PolicyView.swift
개인정보 처리방침 & 서비스 이용약관 URL 연동
- URL 삽입
없음.
|개인정보처리방침|서비스이용약관|
|---|---|
|<img width="511" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/e3f415cc-1b56-4211-b7b2-803840f68e94">|<img width="511" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/d25d3630-b28a-41b5-8c40-134652f9d3de">|
> [Add/#38] 개인정보 처리방침 & 서비스 이용약관 URL 연동

- ABloom/ABloom.xcodeproj/project.pbxproj
- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionWriteView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift
- ABloom/ABloom/Resources/Components/QnAListItem.swift
- SelectQuestionView 구현
- 카테고리 항목을 위해 SelectQuestionViewModel에서 enum 정의
- 카테고리 리스트 뷰 구현
- 버튼 클릭 시 인터렉션 구현
- 챗버블 클릭 시 QuestionWriteView 이동
X
X
> [Feat/35] SelectQuestionView 구현

- ABloom/ABloom/Presentation/BoundaryViews/Connection/ConnectionView.swift
- ABloom/ABloom/Presentation/BoundaryViews/Registration/View/RegistrationView.swift
- ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingView.swift
- ABloom/ABloom/Resources/Components/Buttons.swift
- ABloom/ABloom/Resources/Components/InputFields.swift
fontWithTracking에서 수정된 부분을 적용하였습니다
fontWithTracking에서 파라미터 명시한 부분과 파라미터명 변경된 부분을 수정하였습니다.
머지부탁드립니다!
> [Ref/#48] fontStyle 파라미터 명시 삭제 

- ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingView.swift
- ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingViewModel.swift
> [Fix/#47] 컨플릭트 오류 수정 및 로직 수정

- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift
- ABloom/ABloom/Resources/Components/ChatBubbles.swift
- AnswerWriteView 기능 구현
- TextLimit 150자 구현
- 컴포넌트 수정
- 뒤로 가기 버튼 클릭 시 경고창 구현
X
| 문자길이제한 | 경고창 |
| ![Simulator Screenshot - iPhone 15 Pro - 2023-10-29 at 17 09 48](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/bda1cbd4-1c21-4525-bc7d-06d5b402066a)  | ![Simulator Screenshot - iPhone 15 Pro - 2023-10-29 at 18 17 58](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/22419904-8513-4db4-b7bc-e58096628687) | 
X
> [Feat/66] TextLimit과 경고창 구현

- ABloom/ABloom.xcodeproj/project.pbxproj
- ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
- ABloom/ABloom/Firebase/Firestore/UserManager.swift
- ABloom/ABloom/Firebase/Model/DBAnswerModel.swift
- ABloom/ABloom/Firebase/Model/DBStaticQuestionModel.swift
- ABloom/ABloom/Firebase/Model/DBUserModel.swift
- ABloom/ABloom/Presentation/BoundaryViews/Registration/ViewModel/RegistrationViewModel.swift
- ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
- ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountViewModel.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift
- ABloom/ABloom/Resources/Components/QnAListItem.swift
- ABloom/ABloom/Resources/Extensions/Ex+ Query.swift
답변 확인 뷰에 들어가는 데이터를 불러오는 기능을 구현했습니다.
- 나의 답변 불러오기
- 상대 답변 불러오기
- 에러에 따른 에러 처리용 변수 선언
@Hayun218: 답변을 불러오는 로직에서 발생할 수 있는 경우의 수에 대해, 간단하게 표시해두었습니다. 로직에 맞추어 뷰를 구현하시면 될 것 같습니다!
```swift
// TODO: 성별에 따른 색상 구분
LeftBlueChatBubble(text: answerCheckVM.fianceAnswer.isEmpty ? "상대방의 답변을 기다리고 있어요." : answerCheckVM.fianceAnswer)
// TODO: 답변 상태에 따른 메세지 로직 구현 필요 @Lia
if answerCheckVM.isNoFiance {
LeftBlueChatBubble(text: "상대 없음")
}
if answerCheckVM.isNoFianceAnswer {
LeftBlueChatBubble(text: "상대 답변 없음 ")
}
if answerCheckVM.isNoMyAnswer {
LeftBlueChatBubble(text: "내 답변 없음")
}
```
|내 답변과 상대 답변이 모두 있는 경우|상대 답변만 없는 경우|
|---|---|
|<img width="511" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/5b3d9e45-62fb-4be0-93bd-9f8c2305b19d">|<img width="511" alt="image" …
> [Feat/#75] 답변 확인

- ABloom/ABloom/Firebase/Firestore/UserManager.swift
- ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
홈 뷰에 상대방과 함께 작성한 문답 수를 표시하는 기능을 구현했습니다.
- id 배열 필터를 기반으로 문답을 가져오는 함수를 구현하였습니다.
- 홈 뷰에서 함께 작성한 문답의 개수를 가져오는 함수를 구현하였습니다.
결과 화면 확인
> [Feat/#93] 상대방과 함께 작성한 문항 개수 홈에 표시

- ABloom/ABloom/ABloom.entitlements
- ABloom/ABloom/ABloomApp.swift
- ABloom/ABloom/Firebase/Firestore/UserManager.swift
- ABloom/ABloom/Info.plist
- ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
알림 기능을 위한 세팅을 하였습니다.
- Notification 사용을 위한 기본 세팅
리뷰어가 봐주면 하는 내용을 적어주세요.
> [Feat/#98] notification setting

- ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift
HomeView partner > fiance 명칭을 수정했습니다
HomeView partner > fiance 명칭 수정
없습니다
> [Bug/#106] HomeView partner > fiance 명칭 수정

- ABloom/ABloom.xcodeproj/project.pbxproj
- ABloom/ABloom/Info.plist
- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/NavigationModel.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/SelectQuestionViewModel.swift
- ABloom/ABloom/Resources/Components/ChatBubbles.swift
- AnswerWrite 뷰에서 확인 을 누를 시 MainView 로 이동
- DarkMode 미적용 Info.plist에 명시
- 개요에 작성한 두가지 작업을 진행
현재 질문이 나오지 않지만 규니 말대로 whereField 부분이 안 먹히는 버그여서, 
그 부분 주석하여서 진행하였고, 현재는 주석을 풀어서 올렸습니다.
네비게이션 구현에 대해 생각했는데, 스프린트 2에서 stack의 path를 지정하여야 할 것 같고 지금은 임시로라도 구현하기 위해 NavigationModel을 하나 만들어서 싱글톤으로 값 하나를 넘겨주었습니다. 싱글톤이랑 똑같지만.. EnvironmentObject로 넘길려고 했는데, NavigationLink 안에 들어갈 때 자체버그인 듯 아예 넘어가지지 않아서 결국 이렇게 구현하였습니다!
X
X
> [Feat/100] Navigation&DarkMode

- ABloom/ABloom.xcodeproj/project.pbxproj
- ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
- ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift
- ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
- ABloom/ABloom/Resources/Extensions/Ex+Date.swift
> [Feat/#105] 추천질문 구현

- ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift
- ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
- ABloom/ABloom/Firebase/Firestore/UserManager.swift
- ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/DeleteAccountView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
회원 탈퇴 기능을 구현하였습니다.
- 서브컬랙션 삭제
- 탈퇴 Alert Message
알아서 보세요
> [Feat/#112] 회원 탈퇴 기능 구현

- ABloom/ABloom.xcodeproj/project.pbxproj
- ABloom/ABloom/ABloomApp.swift
- ABloom/ABloom/AppDelegate.swift
Notification 추가 공부 후 Sprint2에서 진행하는 것으로 하여, 현재 코드에서 알림 권한 요청이 오지않도록 비활성화 처리하였습니다.
- AppDelegate 파일로 코드 이동
- Init에서 파이어베이스 초기화 주석 해제하여 실행
> [Chore/91] Notification Inactivated

- ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
추천질문 네비게이션 처리
메인에서 이동한 뷰인지 매개변수를 받아서 처리하였습니다.
> [Bug/123] HomeNavigationIssue

- ABloom/ABloom.xcodeproj/xcshareddata/xcschemes/ABloom.xcscheme
- ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
> [Chore] ProgressView 수정

- ABloom/ABloom.xcodeproj/project.pbxproj
원활한 실기기 테스트를 위한 Provisioning profile을 추가하였습니다.
> [Feat] Provisioning Profile 추가

- ABloom/ABloom.xcodeproj/project.pbxproj
리아가 해결한 네비게이션 백 스와이프 기능이 추가되어, 버전이 업데이트 되었습니다.
> [Chore] 버전 업데이트 ->  v1.0.1

- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerWriteViewModel.swift
남성일 때, ChatBubble 딜레이 ProgressView로 해결
- 딜레이 버그 해결을 위해, 값을 가져올 때까지 ProgressView 삽입
- 확인하였을 때, ProgressView를 뜨는 타임이 짧아서 티가 나지 않으면서 딜레이는 없었음
- 이미지 포함한 컴포넌트 이전에 만들어뒀어서 코드 변경
X
X
X
> [Bug/#139] 남성일 때, ChatBubble 딜레이 ProgressView로 해결

- ABloom/ABloom/Resources/Utilities/ServiceWebURL.swift
고객센터 및 질문제작소 웹 링크를 단축 링크로 수정하였습니다.
- URL 열거형의 웹 링크 주소 변경
없습니다.
|질문제작소|고객센터|
|---|---|
|<img width="511" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/512c9df8-7c3d-48e9-8dc1-0ecb8b806f33">|<img width="511" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/136fd16f-e376-44ad-9825-1477a867bbef">|
> [Feat/#146] 고객센터 및 질문제작소 웹 링크 수정

- ABloom/ABloom.xcodeproj/project.pbxproj
- ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectedView.swift
- ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/ConnectionWaypointView.swift
- ABloom/ABloom/Resources/Components/InputFields.swift
- ABloom/ABloom/Resources/Extensions/Ex+UIApplication.swift
- ABloom/ABloom/Resources/Utilities/ServiceWebURL.swift
키보드 숨김 기능을 구현하였습니다.
- UIApplication을 Extension하여 메서드를 구현하였습니다.
아래 링크를 참고하여 기능을 구현하였습니다.
[블로그 참고](https://seons-dev.tistory.com/entry/CODE-%ED%83%AD%ED%95%98%EC%97%AC-%ED%82%A4%EB%B3%B4%EB%93%9C-%EC%88%A8%EA%B8%B0%EB%8A%94%EB%B0%A9%EB%B2%95-hideKeyboard)
> [Bug/#148] 키보드 숨김 기능 구현

- ABloom/ABloom.xcodeproj/project.pbxproj
- ABloom/ABloom/Info.plist
- ABloom/ABloom/Launch Screen.storyboard
- ABloom/ABloom/Resources/Assets.xcassets/Splash/Splash.imageset/Contents.json
깨지고 포지션이 달라지는 현상을 Constraint 추가 및 이미지 조절 방식을 변경하여 해결
=> 스토리보드 내부에서 변경
| iPhone 15 Pro | iPhone SE |
| ![Simulator Screenshot - iPhone 15 Pro - 2023-11-04 at 16 39 02](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/05b62547-fcc7-4935-b652-2845891f3d29) | ![iPhone SE (3rd generation) - 2023-11-04 at 16 38 26](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/6588afc5-1b9d-4b25-88cb-1714f7fab08e) | 
X
> [Bug/#137] Splash Constraint 추가

- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
- ABloom/ABloom/Resources/Components/ChatBubbles.swift
ChatBubble 성별에 따른 분기처리 컴포넌트 내에서 해결하도록 리팩토링
- ChatBubble 컴포넌트 파일 수정
- 성별 분기 처리 진행한 뷰 작업들 수정
> [Ref/#153] ChatBubble 성별에 따른 분기처리 컴포넌트 내에서 해결

- ABloom/ABloom/AppDelegate.swift
노티 기본 AppDelegate 이해를 위해 블로그 글을 보면서 공부 및 주석처리
- 주석 처리
- 기본이 iOS 16이기에 iOS 10 제한 코드는 불필요하여 삭제
공부한 내용 관련 주석처리만 진행했습니다! 
블로그마다 조금씩 상이하여 완벽하게 이해하지 않았지만, 어느정도 흐름은 파악한 듯 합니다. 
노드 js 파일과 따로 뷰 모델 만들어서 테스트 진행할려고 합니다 :)
X
X
> [Ref/#128] AppDelegate 읽고 주석처리

- ABloom/ABloom/Presentation/CoreViews/Home/View/HomeView.swift
- ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
- ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountView.swift
- ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccount/MyAccountViewModel.swift
- ABloom/ABloom/Resources/Extensions/Ex+Date.swift
결혼예정일 디데이 한국 날짜로 계산하도록 수정
결혼예정일과 now날짜를 한국 날짜로 변환하여 디데이 계산
앞서 추천질문에 사용했던 로직과 유사합니다!
> [Bug/#155] 결혼예정일 디데이 UTC 한국 날짜 계산

- ABloom/ABloom/Firebase/Authentication/AuthenticationManager.swift
- ABloom/ABloom/Presentation/BoundaryViews/Connection/ConnectionView.swift
- ABloom/ABloom/Presentation/BoundaryViews/Registration/View/RegistrationView.swift
- ABloom/ABloom/Presentation/CoreViews/Menu/SubViews/MyAccountConnecting/MyAccountConnectingView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
> [Bug] QA 반영 Keyboard 숨기기, 회원탈퇴 로직 일부 수정

- ABloom/ABloom/Resources/Extensions/Ex+Date.swift
결혼날짜 디데이 버그를 수정했습니다.
"일"로만 계산되던 부분을 수정했습니다.
없슴다
> [Bug/#166] 결혼날짜 디데이 버그 수정

- ABloom/ABloom/Resources/Utilities/ServiceWebURL.swift
> [Bug] 고객 센터 URL 수정

- ABloom/ABloom.xcodeproj/project.pbxproj
> [Feat] 버전 업데이트 -> 1.0.2

- ABloom/ABloom.xcodeproj/project.pbxproj
- ABloom/ABloom/Firebase/Firestore/UserManager.swift
- ABloom/ABloom/Firebase/Model/DBAnswerModel.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
- ABloom/ABloom/Resources/Utilities/ReactionType.swift
리액션을 하는 기능을 구현했습니다.
- Answer 모델에 프로퍼티가 추가 되었습니다.
- reaction -> 반응 유형에 따른 저장 값
- isComplete -> 문답 완성 상태
- getAnswer() 함수의 리턴 값이 추가되었습니다.
- answerCheckViewModel의 Answer 값이 String에서 DBAnswer로 변경되었습니다.
- ReactionType 열거형이 추가되었습니다.
- @JINi0S  리액션과 관련된 뷰 작업을 진행해주세요
| Header | Header |
| <img width="200" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/145ef22e-68d0-4525-8cc2-a39d7dbbdfa9"> | <img width="297" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/77708819/6a0c57c4-a85d-448b-a163-f6ab4e12b90d"> |
> [Feat/#179] 리액션 기능 구현

- ABloom/ABloom/Firebase/Firestore/UserManager.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
- ABloom/ABloom/Resources/Utilities/ReactionType.swift
리액션 및 문답 완성 로직 구현
- 리액션과 문답 완성에 따른 로직과 뷰에 적용될 플래그를 구현했습니다.
- 문답을 완성하는 액션을 취할 수 있는 기능을 구현했습니다.
- 리액션에 따른 텍스트를 구현하였습니다.
- @JINi0S 상황에 따른 뷰 구성을 간단하게 작성했습니다. GitHub 리뷰로 보기엔 조금 양이 많을 수 있으니, 주석을 참고하셔서 뷰를 구현하시면 될 것 같습니다.
- 구현에 너무 힘을 많이 쓴 관계로 의문 사항은 내일 구두로 설명 드리도록 하겠습니다... 의문점 피드백 남겨주세요!
> [Feat/#179] 리액션 및 문답 완성 로직 구현

- ABloom/ABloom.xcodeproj/project.pbxproj
- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/TipView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
- ABloom/ABloom/Resources/Utilities/AnswerStatus.swift
문답 확인 뷰 레이아웃 수정
작업 내용을 자세히 적어주세요.
리뷰어가 봐주면 하는 내용을 적어주세요.
리뷰어의 이해를 위해 스크린샷을 추가해주세요. 
변경한 로직에 대해 추가로 공유하고 싶은 내용이 있다면 작성해주세요.
개발을 하시면서 발견하신 새로운 점을 팀원들에게 공유해주세요.
해결되지 않은 문제가 있다면 팀원들이 확인하도록 적어주세요.
> [Design/#182] 문답 확인 뷰 레이아웃 수정

- ABloom/ABloom.xcodeproj/project.pbxproj
- ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
- ABloom/ABloom/Resources/Extensions/Ex+String.swift
SelectQuestionView 수정
- 글자 개행 Extension 추가
- 단어 단위가 아니라 글자 단위로 띄어쓰기가 진행해서 width가 동일하도록 유지
X
X
> [Feat/#185] SelectQuestionView 글자 개행 도입 및 패딩 일부 수정

- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/QuestionMainViewModel.swift
QuestionMainViewModel 문답 완성된 조건이 없어서 조건을 추가했습니다.
QuestionMainViewModel 문답 완성 조건을 추가했습니다.
더 효율적인 코드가 있을까요
> [Feat/#190] QuestionMainViewModel 문답 완성상태 조건 추가

- ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
완성된 문답의 개수를 표시하는 로직을 수정하였습니다.
- getQnACount() 함수의 로직을 수정하였습니다.
- 나의 응답 중 완성된 응답을 필터로 사용
- 상대 응답 중 완성된 응답의 개수를 리턴
없어요
> [Feat] 완성된 QnA 개수 로직 수정

- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerWriteView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
AnswerWrite뷰에서 탈출할 때 스와이프 재활성화 진행
- 스와이프 재활성화 코드 추가
X
X
X
> [Bug/#199] 스와이프 재활성화

- ABloom/ABloom/Resources/Components/ChatBubbles.swift
- 기존에는 폰트 값 조절으로 만든 이슈였는데, 우선 디자인 요청사항만 적용
- minWidth 값 조절
ChatBubble에서 minWidth 조절
X
X
X
> [Design/#186] minWidth 값 수정

- ABloom/ABloom/Firebase/Model/DBAnswerModel.swift
- ABloom/ABloom/Presentation/CoreViews/Home/ViewModel/HomeViewModel.swift
벤틀리의 요청으로 홈 화면에 표시 되는 문답 수를 완성한 문답 수 에서 작성한 문답 수로 변경하였습니다.
- 홈 화면에 문답 수 카운트 로직 변경
없음
> [Feat/#207] 완성하지 않아도 작성한 문답 개수를 홈화면에 표시

- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
문답확인뷰에 스크롤을 적용합니다.
문답확인뷰에 스크롤을 적용했습니다.
문답확인뷰의 응답완료 상태 챗버블 순서를 변경했습니다.
없습니다
> [Feat/#200] 문답확인뷰 Scroll 적용

- ABloom/ABloom/Presentation/CoreViews/QnA/View/AnswerCheckView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/View/TipView.swift
- ABloom/ABloom/Presentation/CoreViews/QnA/ViewModel/AnswerCheckViewModel.swift
- ABloom/ABloom/Resources/Components/ChatBubbles.swift
문답확인뷰 반응 업데이트하는 로직 수정
팁뷰를 재수정했습니다 ^,^,,
문답확인뷰 반응 업데이트 로직을 클릭하면 바로 업데이트되도록 재수정했습니다.
읍심다
> [Feat/#212] 문답확인뷰 반응 업데이트 로직 재수정

- ABloom/ABloom/Resources/Components/CategoryQuestionBox.swift
- ABloom/ABloom/Resources/Components/ChatBubbles.swift
- ABloom/ABloom/Resources/Extensions/Ex+String.swift
숫자 포함시 줄바꿈 현상 해결
- 임시로 분기처리 진행
> [Bug] 숫자 포함시 줄바꿈 현상 해결

- ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Contents.json
- ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 100.colorset/Contents.json
- ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 200.colorset/Contents.json
- ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 300.colorset/Contents.json
- ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 400.colorset/Contents.json
- ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 50.colorset/Contents.json
- ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 500.colorset/Contents.json
- ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 600.colorset/Contents.json
- ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 700.colorset/Contents.json
- ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 800.colorset/Contents.json
- ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 900.colorset/Contents.json
- ABloom/ABloom/Resources/Assets.xcassets/colors/Gray/Gray 950.colorset/Contents.json
> [Design/#222] Gray Color Asset 추가

- ABloom/ABloom/Firebase/Firestore/AnswerManager.swift
- ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerView.swift
- ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerViewModel.swift
- ABloom/ABloom/Resources/Components/CustomNavigationBarModifier.swift
답변작성뷰 저장 기능 합치기
- 저장 기능 구현 
- Swipe 컨트롤하는 함수 뷰모델로 구현
- 패딩값 조절
- 키보드가 생겼을 때 뷰 이동 현상 제어 => ScrollView로 해서 고정시킴,,
스와이트하는 부분을 변수로 처리해서 onChage 함수로 처리할려 했는데, 잘 작동하지 않아 뷰모델에서 구현하는 형태로 바꾸었습니다.
저장 기능 테스트는 질문을 제대로 불러오도록 하는 기능 머지를 진행 후에 하겠습니다!! 
X
> [Feat/#265] 답변저장하는 기능 합치기

- ABloom/ABloom/Firebase/Firestore/StaticQuestionManager.swift
- ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointView.swift
- ABloom/ABloom/Presentation/Main/CreateAnswer/CategoryWaypoint/CategoryWaypointViewModel.swift
- ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift
- ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionViewModel.swift
질문 선택, 추천질문 데이터 연동
- 질문 선택 뷰 모델 컴바인 sink 적용 
- 추천질문 로직 다듬기
- 질문 선택 뷰 버그 해결 (초기 탭 선택 관련)
추천 질문 로직은 모든 질문 완료 시 아직 답변이 없는 질문들 중에서 랜덤하게 뽑아서 진행했습니다!
X
X
> [Feat/#281] 실시간 데이터 연동

- ABloom/ABloom/Firebase/Firestore/AnswerManager.swift
- ABloom/ABloom/Firebase/Model/DBAnswerModel.swift
- ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerView.swift
- ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerViewModel.swift
- ABloom/ABloom/Presentation/Main/QnAList/QnAListItem.swift
- ABloom/ABloom/Presentation/Main/QnAList/QnAListViewModel.swift
문답리스트뷰, 문답확인 동기화 작업을 진행했습니다
문답리스트뷰, 문답확인뷰 동기화 작업을 진행했습니다
읍습니다
> [Feat/285] 문답리스트뷰, 문답확인뷰 Answers Combine 동기화 작업, 질문에 숫자가 포함될 경우 수정

- ABloom/ABloom/Presentation/Main/CreateAnswer/SelectQuestion/SelectQuestionView.swift
- ABloom/ABloom/Presentation/Main/CreateAnswer/WriteAnswer/WriteAnswerView.swift
- AnswerWrite 문구 수정
- SelectQ 로그인 X 시 문구 수정
> [Ref] 문구수정

- .gitignore
- ABloom/ABloom.xcodeproj/project.pbxproj
- ABloom/ABloom/AppDelegate.swift
믹스패널 토큰 gitignore 적용
- 믹스패널 토큰 저장을 위한 Plist 생성
- git cache 초기화 => gitignore 수정 적용 위함
plist는 슬랙에 따로 올려두겠습니다!
> removed cached&mixPanelToken

- ABloom/ABloom.xcodeproj/project.pbxproj
- ABloom/ABloom/Firebase/Firestore/AnswerManager.swift
- ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerViewModel.swift
알림 기능을 위해서 작성한 코드로 인해 뷰에서 반응이 수정되지 않는 버그 수정
DB 업데이트하는 순서를 교환하여 해결
> [Bug/#346] 반응 수정 적용

- FirebaseFunction/functions/index.js
알림 관련하여 JS 코드 수정
- is_complete 필드가 False 에서 True로 변환 될 때, 양쪽 모두에게 알림이 가도록 했었는데, 코드 상에서 is_complete 필드를 나와 상대방것 모두 바꿔주기에 본인에게만 알림이 가도록 변경
- Reaction 알림의 경우, is_complete 필드가 True일 때는 보내지 않도록 추가
> [Bug/#340] JS 코드 수정
